AWSTemplateFormatVersion: 2010-09-09
Description: EventBridge Rule and SNS topic template

Resources:
  # definition of sns topic
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MyNotificationTopic

  # EventBridge Rule
  MyEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: MyCustomRule
      Description: "Rules to detect custom events"
      EventPattern: |
        {
          "source": ["aws.cloudwatch"],
          "detail-type": ["CloudWatch Alarm State Change"],
          "detail": {
            "$or": [{
              "alarmName": [{
                "prefix": "dev-test-"
              }]
            }, {
              "alarmName": [{
                "prefix": "stg-test-"
              }]
            }]
          }
        }
      State: ENABLED
      Targets:
        - Arn: !Ref MySNSTopic
          Id: "SNSTarget"

  # action policy of sns
  TopicInlinePolicy:
    Type: AWS::SNS::TopicInlinePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "SNS:GetTopicAttributes"
              - "SNS:SetTopicAttributes"
              - "SNS:AddPermission"
              - "SNS:RemovePermission"
              - "SNS:DeleteTopic"
              - "SNS:Subscribe"
              - "SNS:ListSubscriptionsByTopic"
              - "SNS:Publish"
            Resource: !Sub "arn:aws:sns:ap-northeast-1:${AWS::AccountId}:${MySNSTopic}"
            Condition:
              StringEquals:
                "AWS:SourceOwner": !Sub ${AWS::AccountId}
          - Sid: AllowPublishFromSpecificEventBridge
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: sns:Publish
            Resource: !Ref MySNSTopic
      TopicArn: !Ref MySNSTopic
