AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:
  SysName:
    Type: String
    Description: System name.
  EnvName:
    Type: String
    Description: Environment name. ex. dev, stg, prd.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC id.
  VpcEndpointIps:
    Type: CommaDelimitedList
    Description: API Gateway's VPC endpoint id.
  SecurityGroupsForNlb:
    Type: CommaDelimitedList
    Description: security groups to attach to nlb.
  NlbStaticIps:
    Type: CommaDelimitedList
    Description: private ip to assign to nlb.
  NlbSubnetIds:
    Type: CommaDelimitedList
    Description: Subnet groups to attach to nlb.
  CertificateArn:
    Type: String
    Description: The default SSL server certificate arn for a secure listener.

Resources: 
  TargetGroupForVpcendpointForNlb:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${SysName}-${EnvName}-tg-for-nlb
      Port: 443
      Protocol: TLS
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: traffic-port
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Targets:
        - Id: !Select [ "0", !Ref VpcEndpointIps ]
          Port: 443
        - Id: !Select [ "1", !Ref VpcEndpointIps ]
          Port: 443
      Tags:
        - Key: Name
          Value: !Sub ${SysName}-${EnvName}-nlb-tg

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${SysName}-${EnvName}-nlb
      Scheme: internal
      Type: network
      SecurityGroups: !Ref SecurityGroupsForNlb
      SubnetMappings:
        - PrivateIPv4Address: !Select [ "0", !Ref NlbStaticIps ]
          SubnetId: !Select [ "0", !Ref NlbSubnetIds ]
        - PrivateIPv4Address: !Select [ "1", !Ref NlbStaticIps ]
          SubnetId: !Select [ "1", !Ref NlbSubnetIds ]
      Tags:
        - Key: Name
          Value: !Sub ${SysName}-${EnvName}-nlb

  NlbTlsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 443
      Protocol: TLS
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupForVpcendpointForNlb
      Certificates:
        - CertificateArn: !Ref CertificateArn
